### ISSUE TITLE
Maintenance and Wishlist to support upcoming 13.1 release

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji.org#140]
- Update to node 14.x (also in `.nvmrc` file)

**Library**
- enhance emoji detail modal to support multiskintones. Basically add a second skintone selector if it is a multiskintone emoji
- library (list view): just show the skintone_base_emoji and don’t show deduced multiskintone emojis. Filter: `e.skintone_combination !== multiple`
- add to sort/filter dropdown “have skintones”. Filter `e.skintone_combination === single`
- add to sort/filter dropdown “have multi-skintones”. Filter `currentEmoji.skintone_combination === single and if find openmojis.skintone_combination === multiple with same openmojis.skintone_base_hexcode = currentEmoji.hexcode `
- fix broken css style for background of sort/filter dropdown

⬇️ (nice to have)

**General**
- add [svg favicon](https://css-tricks.com/svg-favicons-and-all-the-fun-things-we-can-do-with-them/), use [1F64B](https://openmoji.org/library/#search=1F64B&emoji=1F64B) as asset
- add [openmoji twitter link](https://twitter.com/OpenMoji) next to GitHub link on the top
- remove twitter link in footer
- fix #99
- add general OpenGraph Tag like the one of https://github.com/hfg-gmuend/openmoji

**Special Interest Categories**
- would be nice to showcase there randomly more categories of extra-openmoji e.g. healthcare, climate-environment etc.

**Mobile**
- landing site: show more emojis in the helo big teaser section. Maybe simply smaller and more?
![IMG_E0C93B17FD90-1](https://user-images.githubusercontent.com/480224/118631666-059a2200-b7d0-11eb-9132-8fbe94a3bc0f.jpeg)

**Comment by carlinmack** [comment]
https://realfavicongenerator.net just added an inbuilt SVG favicon editor

**Comment by carlinmack** [comment]
https://realfavicongenerator.net just added an inbuilt SVG favicon editor

**Comment by b-g** [comment]
Hi @PaulRaschke Many thanks for this! Great! 

- Tiny bug: missing image
![2021-07-01 at 09 49](https://user-images.githubusercontent.com/480224/124087040-ebe82d80-da51-11eb-861b-6694a53b9006.jpg)

- And I would find it more logical and more consitent to put the folder `/src/favicons/` to `/img/favicons/`

Otherwise this is ready to go (please deploy afterwards and close this issue). M A N Y  T H A N K S for this! This will keep the OpenMoji.org fresh and maintained for 2021!! 🙏❤️

**Comment by PaulRaschke** [comment]
Hi @b-g,

> Tiny bug: missing image

I think there shouldn't be an image in the first place, or should it? On the deployed instance https://openmoji.org/ none is displayed and when evaluating this code part https://github.com/hfg-gmuend/openmoji.org/blob/7b176ea65cc8a85119602b7885316ae17911d93b/src/general.js#L3-L9 it's just appended to the header because `window.location.pathname` is `"/openmoji.org/"` instead of `"/"` on the GitHub Pages instance.

I've moved the favicons :)

Great to hear!

**Comment by b-g** [comment]
Hi @PaulRaschke, 

- Many thanks for refactoring the favicon folder! 
- Many thanks for the Adleraugen! Yes you are right, landing header shouldn't have this image. Please remove.

then please deploy :)

**Comment by PaulRaschke** [comment]
Deployed! 🎉
