### ISSUE TITLE
Upgrade Github Action SamKirkland/FTP-Deploy-Action to latest version

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji.org#157]
We are using a quite old version, see https://github.com/SamKirkland/FTP-Deploy-Action/releases

**Comment by stephanbogner** [comment]
**✅ Done**

- Testing the latest version (commit 791a851db2a3cf3b0e54b60f80816a1d2c22c7b9)
- First deploy with correct server configuration (commit 3e9c55ec93f005af723dca2b4e0985e807b155b3)
- Thanks to a bug I also verified that it actually only uploads changed files 😅
