### ISSUE TITLE
What to do with broken FTP-Deploy-Action?

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji.org#158]
Hi @stephanbogner, 

The FTP-Deploy-Action run was completed https://github.com/hfg-gmuend/openmoji.org/actions/runs/1956258529 ... but the website on https://openmoji.org/ is still the old one. It seems not to be working :(

Are you willing once more to investigate, or should we fall back to old school ftp?

**Comment by stephanbogner** [comment]
Weirdly it did upload ... but to `/docs`, even though `server-dir` should default to `./` 🤔 
(Aren't we already doing old school FTP? 😅)

- I tried to explicitly stated `server-dir`, but that apparently wasn't available in the version we use.
- I tried upping the version (also regarding #157) , but then login to FTP doesn't work. I assume because [it was changed how the server argument works](https://github.com/SamKirkland/FTP-Deploy-Action/blob/master/migration.md#how-to-upgrade) (it was split up into multiple arguments).

→ I am only available for 1 more hour today and don't want to break the live website, so I am gonna fix the settings tomorrow.

**Comment by b-g** [comment]
I see :) ... + Great/no rush! Glad that you will look into it.

**Comment by stephanbogner** [comment]
@b-g 

Ok, so I just checked.
✅ It's working with my server with the following settings:
````
[...]
server: lab.stephanbogner.de
username: ${{ secrets.FTP_STEPHANBOGNER_USERNAME }}
password: ${{ secrets.FTP_STEPHANBOGNER_PASSWORD }}
[...]
````
❌ ... but it doesn't work with:
````
[...]
server: openmoji.org
username: ${{ secrets.FTP_USERNAME }}
password: ${{ secrets.FTP_PASSWORD }}
[...]
````
❌ or:
````
[...]
server: ${{ secrets.FTP_SERVER   }}
username: ${{ secrets.FTP_USERNAME }}
password: ${{ secrets.FTP_PASSWORD }}
[...]
````
→ I receive `Error: FTPError: 530 Login incorrect.`

I assume username and password is correct as it worked before, so it must be the server.

**→ Could you check what the correct URL for the server is? (e.g. by logging in via CyberDuck)**
(Github unfortunately doesn't allow my look at the current values 😞)

**Comment by stephanbogner** [comment]
My guess from the [old migration guide](https://github.com/SamKirkland/FTP-Deploy-Action/blob/3.1.1/v2-v3-migration.md#breaking-changes) is, that it's currently written like `ftp://some-server.com` but should in the new version only be `some-server.com`

**Comment by b-g** [comment]
OK. Many thanks for investigating! Did send you the logins details via Signal messenger ... please overwrite the Github secrets.

**Comment by stephanbogner** [comment]
**It's finally live**  🎉 🙂 
(The new credentials did the trick!)

@b-g Can you check [this PR](https://github.com/hfg-gmuend/openmoji.org/pull/159) so we merge the final changes in production back into main?
And maybe also do a quick check, but on my end everything looks good in Chrome, Firefox and Mobile Safari.

**Comment by b-g** [comment]
@stephanbogner YAY! YAY!! The eagle has landed! Yes plz merge the PR!

> And maybe also do a quick check, but on my end everything looks good in Chrome, Firefox and Mobile Safari.

Looks good! Thanks again!! Found some tiny things on mobile ... and there seems to be a general problem with /library for Firefox Mobile (iOS). But not sure whether it worth to optimize for such a tiny iOS niche browser.

https://github.com/hfg-gmuend/openmoji.org/issues/160
