### ISSUE TITLE
Write a few nice astro tech tweets (after fixes and final deployment)

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji.org#165]
Would be nice to tweet about the new tech stack at our twitter channel cc @stephanbogner

**Comment by stephanbogner** [comment]
Totally agree, once done, I also want to add it to the [Astro showcase](https://astro.build/showcase/) via [this form](https://github.com/withastro/astro.build/issues/new/choose)

**Comment by stephanbogner** [comment]
Hey @b-g 

**(1)** [I submitted OpenMoji to the Astro Showcase](https://github.com/withastro/astro.build/issues/104)

**(2)** I think we are ready to send tweets. Proposal, but feel free to change:

`🎉 Now every emoji has its own page – check it out yourself: https://openmoji.org/library/emoji-1F389/`
<img width="1200" alt="unique page" src="https://user-images.githubusercontent.com/7897006/166101471-9f11bf98-de8c-4251-bb20-499bdccd3f9b.png">

`👋 We completely revamped OpenMoji.org using @astrodotbuild. It's now much easier to keep up-to-date but also with 
a page for each emoji 🔥 and search with suggestions 🕵️‍♀️!`
<img width="1200" alt="openmoji-love-astro" src="https://user-images.githubusercontent.com/7897006/166101479-bd2b9445-639e-47c0-8a2c-6c6e4ddf0c4e.png">

**Comment by stephanbogner** [comment]
We are now on the [showcase](https://astro.build/showcase/) ... not particularly close to the top, but nevertheless 😄 

<img width="1280" alt="Screenshot 2022-05-03 at 10 17 27" src="https://user-images.githubusercontent.com/7897006/166422986-77b7f8de-3377-4c66-a6c2-9e65561a0749.png">

**Comment by b-g** [comment]
YAY! Thanks!
