### ISSUE TITLE
Broken Astro install? "Unable to parse HTML; Element is missing end tag."

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji.org#189]
Hi @stephanbogner, 

Sorry to bother, but I have an odd Astro error ... you might have encountered in the past.

If I do a new checkout this repo and then:

```
nvm use
npm i
npm start
```

Firing up the browser with http://127.0.0.1:3000/ works fine, but if I open some OpenMoji details site http://127.0.0.1:5500/library/emoji-1F3C0/ I get this strange error:
<img width="1623" alt="Screen Shot 2024-02-23 at 09 41 36" src="https://github.com/hfg-gmuend/openmoji.org/assets/480224/23122575-0200-4e80-9f7c-c5cb5e453c50">

In addition running `npm run build` works, the entire site is generated and browsing it yields no errors in the console log of the browser.

Could it be that a dependencies hasn't been 100% freezed back in the days?

It is kind of hard now to add new features as impossible to test locally e.g. PR #185 

Any advice?

**Comment by stephanbogner** [comment]
Maybe it's because there is a `<p>` tag inside another `<p>` tag which might not be valid/correct HTML.

If that doesn't do the trick, ping me again and I'll have a more detailed look.

**Comment by b-g** [comment]
Many thanks!!! Yes that was the problem ... is seems the emojiPedia.description text are malformated and introduced with the lastest pull from Emojipedia data this bug. Uff. I did a quick fix. Sorry to bother you!!

**Comment by stephanbogner** [comment]
No worries, you're welcome :)

PS: Let me know once you are in Ulm again. I still have a small present for you ;)

**Comment by b-g** [comment]
Thanks! Will do! 👍

**Comment by s-light** [comment]
that was exactly what i got in https://github.com/hfg-gmuend/openmoji.org/issues/184
