### ISSUE TITLE
the link to 'openmoji-abc.svg' opens the raw file rather than downloading the file

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji.org#99]

**Comment by b-g** [comment]
Could be fixed by introducing another php proxy, like https://github.com/hfg-gmuend/openmoji-website/blob/master/php/download_from_github.php

**Comment by carlinmack** [comment]
I've learned that you can actually just set the `download` parameter in the link https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Attributes

**Comment by carlinmack** [comment]
Hmm the attribute is there and if you link to a website it will download the html page. Not sure why the behaviour is different for SVG
